version: '3.5'
services:
  nest-api:
    image: glrd/card-memory-api
    build:
      context: ./
    container_name: card-api
    command: bash -c 'pm2-runtime start ecosystem.config.js -i max'
    environment:
      - APP_PORT:3000
    links:
      - nest-mysql
    ports:
      - "3000:3000"

  nest-mysql:
    image: mysql:5.7
    container_name: nest-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=card-memory
    ports:
      - 3306:3306
